#! bin/bash
# CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 evaluation.py --model_path "checkpoint/FF++/ViTSingle-rm2-h16-LD2-frr16-cspdarknet53-FF++" --use_model_percent 0.2 --dataset_dir_test "/hdd1/DeepFakes_may/FF++/raw/"
# CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 evaluation.py --model_path "checkpoint/FF++/ViTSingle-rm2-h16-LD2-frr16-cspdarknet53-FF++" --use_model_percent 0.2 --dataset_dir_test "/hdd1/DeepFakes_may/FF++/c23/"
# export CUDA_VISIBLE_DEVICES=0; python -m torch.distributed.launch --nproc_per_node=1 evaluation.py --model_path 'checkpoint/FF++/ViTSingle-rm2-h16-LD2-frr16-cspdarknet53-FF++' --use_model_percent 0.2 --dataset_dir_test '/hdd4/DeepFakes_may/FF++/c40/'
# export CUDA_VISIBLE_DEVICES=0; python -m torch.distributed.launch --nproc_per_node=1 evaluation.py --model_path 'checkpoint/FF++/ViTSingle-rm5-h16-LD2-frr16-cspdarknet53-FF++' --use_model_percent 0.5 --dataset_dir_test '/hdd1/DeepFakes_may/FF++/raw/'
# CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 evaluation.py --model_path "checkpoint/FF++/ViTSingle-rm5-h16-LD2-frr16-cspdarknet53-FF++" --use_model_percent 0.5 --dataset_dir_test "/hdd1/DeepFakes_may/FF++/c23/"
# CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 evaluation.py --model_path "checkpoint/FF++/ViTSingle-rm5-h16-LD2-frr16-cspdarknet53-FF++" --use_model_percent 0.5 --dataset_dir_test "/hdd4/DeepFakes_may/FF++/c40/"
# CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 evaluation.py --model_path "checkpoint/FF++/ViTSingle-rm8-h16-LD2-frr16-cspdarknet53-FF++" --use_model_percent 0.8 --dataset_dir_test "/hdd1/DeepFakes_may/FF++/raw/"
CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 evaluation.py --model_path "checkpoint/FF++/ViTSingle-rm8-h16-LD2-frr16-cspdarknet53-FF++" --use_model_percent 0.8 --dataset_dir_test "/hdd1/DeepFakes_may/FF++/c23/"
CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 evaluation.py --model_path "checkpoint/FF++/ViTSingle-rm8-h16-LD2-frr16-cspdarknet53-FF++" --use_model_percent 0.8 --dataset_dir_test "/hdd4/DeepFakes_may/FF++/c40/"